version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_bus
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
      # - rabbitmq_data:/var/lib/rabbitmq/ # Optional: persist data
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
# volumes: # Optional: define if you uncommented above
#   rabbitmq_data:
